### ISSUE TITLE
Get the position of the marker

### ISSUE THREAD

**Issue by vatanbytyqi** [ashleyw/react-sane-contenteditable#12]
Hi,
I have a toolbar with some clickable elements and I want to append some text on the position of the marker when a button is clicked in the toolbar. Can I somehow retrieve this from your react-sane-contenteditable
? My Parent component knows the content but can it also track where the input marker is positioned so that it can append stuff in the correct position?

**Comment by ashleyw** [comment]
It should be possible, but I'm not exactly sure how. Deep text-editor features were out of the original scope of this project. Perhaps https://draftjs.org/ would be more applicable to your use-case?
