### ISSUE TITLE
Multiple new lines get collapsed on blur

### ISSUE THREAD

**Issue by varunudacity** [ashleyw/react-sane-contenteditable#13]
Why does this library go to great pains to remove new lines?

**Comment by ashleyw** [comment]
It was a requirement we had. If you'd like to submit a patch to allow
disabling it, I'd gladly merge it in.

Out of interest, what is your use case where you'd like to allow multiple
new lines?

On Sat, 4 Aug 2018 at 04:31 varunudacity <notifications@github.com> wrote:

> Why does this library go to great pains to remove new lines?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
-- 
t: @ashleyw <http://twitter.com/ashleyw>
w: ashleyw.co.uk

**Comment by ashleyw** [comment]
Closing this issue for now, but feel free to re-open if you have anything further to add.
