### ISSUE TITLE
Issues with accessing Synthetic event onKeyDown

### ISSUE THREAD

**Issue by nijk** [ashleyw/react-sane-contenteditable#14]
Firstly, thanks for providing this component it's really useful and simple to use!

I'm seeing some odd behaviour relating to synthetic events when using this lib, I'm unable to access the event object properties in a `onKeyDown` handler provided to `<ContentEditable />`. I believe this is down to React's Event polling, which as far as I can tell works fine for synchronous access to the event but not async access.  At present this component is calling `this.props.onKeyDown` wrapped inside a `setTimeout`, which I believe is causing my particular issue.

I can't see any detrimental effects from removing the `setTimeout` and calling `this.props.onKeyDown` at the end on the `_onKeyDown` instance method when using this component in a React 16.4.0 project, however I'm sure this code would be here for a good reason, so I'm wondering what the reason is for needing it?

I'm happy to raise a PR for the change as I'd prefer to contribute than rely on a forked lib.

**Comment by ashleyw** [comment]
Hi @nijk!

`setTimeout` was introduced by @ethanlee16 here: https://github.com/ashleyw/react-sane-contenteditable/pull/6

If you can figure out a solution to both problems I'd be happy to review and pull in your PR! Bonus points if you can write a couple of tests to confirm you're not breaking any existing features! ;)

**Comment by ashleyw** [comment]
Good work! Will look out for your PR.

I've been meaning to get a test suite setup, I just haven't had the time unfortunately. If you could help with that, it would be great! 👍🏼

**Comment by nijk** [comment]
@ashleyw PR is in now. If you are happy to add me as a collaborator, then I can get involved with the test suite you mentioned.

**Comment by ashleyw** [comment]
@nijk added you as a collaborator 👍🏼 Found a couple of bugs (unrelated to your PR), so I'm going to try and jump in next week and write some tests.

A major version bump would be appropriate to standardise and cleanup the API. Interested in hearing your thoughts on that.

Thanks!
