### ISSUE TITLE
shouldComponentUpdate blocks re-render on props not in propTypes

### ISSUE THREAD

**Issue by nijk** [ashleyw/react-sane-contenteditable#19]
So if I pass a prop that is not in the propTypes for this component, i.e. a prop that I might be passing to a styledComponent that I'm using as the `tagName` and I happen to pass that prop after the initial render then the current implementation of `shouldComponentUpdate` returns false.

**Comment by ashleyw** [comment]
Fixed in https://github.com/ashleyw/react-sane-contenteditable/commit/7f84594cd6e1f48c9173b8facf4cd916bf427cce
