### ISSUE TITLE
handleChange not triggering

### ISSUE THREAD

**Issue by armandofreire** [ashleyw/react-sane-contenteditable#2]
Hi Ashley!

I just implemented the react-sane into my application but it doesnt trigger the onChange event!

I'm binding the method on the constructor, the method exists and I placed the component on my render method. It renders correctly but doesnt trigger the handleChange! Here's the code!

**binding on the constructor**
```javascript
    this.handleChange = this._handleChange.bind(this);
```

**exposing the method**
```javascript
_handleChange(ev, value) {
    console.log('aaaaa'); // won't trigger
    this.setState({ title: value });
}
```

**render**
```javascript
<ContentEditable
    tagName="div"
    styleName="message-field"
    content={ this.state.title }
    editable={ true }
    maxLength={ 10 }
    placeholder="Digite uma mensagem..."
    multiLine={ true }
    onChange={ this.handleChange }
/>
```

Could you give me a hand, please? :-)

**Comment by jesstelford** [comment]
This works for me. Note that the `onChange()` event may not fire for every key press. This is due to the sanitization - if the sanitized input hasn't changed, then no `onChange()` event will be triggered.

**Comment by ashleyw** [comment]
@armandofreire If you could put together a minimal example project of your issue, I'll take a look 👍🏼For now I'm going to close this issue. Thanks!
