### ISSUE TITLE
Unexpected identifier error

### ISSUE THREAD

**Issue by paschaldev** [ashleyw/react-sane-contenteditable#30]
Trying to run this plugin on next.js (SSR) and I got the error below. I inspected the source and I see it still contains `import` and `export` statement.

```
Unexpected identifier
/Users/xyz/Documents/Gitlab/jet/node_modules/react-sane-contenteditable/lib/index.js:29
import React, { Component } from 'react';
       ^^^^^
```

**Comment by nijk** [comment]
Thanks for the PR I'll take a look later today.

I can't comment on why that was done, perhaps @ashleyw knows?

**Comment by paschaldev** [comment]
#32

**Comment by paschaldev** [comment]
We need to transform to common JS syntax so that most browsers can execute it. This is from babel docs.

> modules
"amd" | "umd" | "systemjs" | "commonjs" | false, defaults to "commonjs".

Enable transformation of ES6 module syntax to another module type.

Setting this to false will not transform modules.

**Comment by nijk** [comment]
@paschaldev Can this issue be closed now?
