### ISSUE TITLE
Unconnected with state

### ISSUE THREAD

**Issue by paschaldev** [ashleyw/react-sane-contenteditable#31]
Plugin does not re-render when you manually edit the state e.g from react dev tools. HOwvere the state changes from the onChange event trigger.

Any other place you try to update the value that holds the state doesn't affect the component, the value remains the same and not equal to the state.

**Comment by nijk** [comment]
I guess I'm a little confused as to why you need to alter the component's
local state directly. Does passing the new value as a prop to the component
not do what you expect?

**Comment by nijk** [comment]
Oh ok, that makes sense then. I'll take a look at this too.

In the meantime as a workaround you could set the `innerText` value of the `ref` obtained from `innerRef `.

**Comment by paschaldev** [comment]
Alright

**Comment by kjrandez** [comment]
It seems like "content" prop is only referenced at initialization. So that means the parent component can not actually control the content using it's own state within render(). Content is only be updated when user types directly into the ContentEditable.

Is that right?

**Comment by nijk** [comment]
@kjrandez Yes that's about right, the component behaves in a rather unconventional way that is neither a [controlled](https://reactjs.org/docs/forms.html#controlled-components) nor [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html) component. What is being requested here is for the component to behave in a predictable way as a controlled component via props passed to `<ContentEditable />`. I agree with that this request is the right way to change the component and have a [maintenance roadmap](https://github.com/ashleyw/react-sane-contenteditable/issues/33) (see #5) to address this issue.

**Comment by nijk** [comment]
@paschaldev Just to keep you updated, I'm currently working on this one.

**Comment by jstriebel** [comment]
@nijk Any news on this? This is an important issue to make this Component usable two ways (allowing user input and changing the content in the code).

My best guess is that [`shouldComponentUpdate`](https://github.com/ashleyw/react-sane-contenteditable/blob/master/src/react-sane-contenteditable.js#L68-L71) is not working, you need also to check if the state has changed.
Also, note that [`componentWillReceiveProps` is deprecated])https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops).

**Comment by nijk** [comment]
@jstriebel I am still working on this but haven't had much time since my last update. That said I should be able to pick this up again very soon. 

I agree with you that this is an important issue to fix, in the meantime I can only suggest that you use the [workaround I suggested](https://github.com/ashleyw/react-sane-contenteditable/issues/31#issuecomment-413487762) until I have been able to complete my rewrite of the component.

**Comment by pfischer1290** [comment]
Hi guys.

just sent a PR to fix this issue. Thanks for merging and updating the npm package.

https://github.com/ashleyw/react-sane-contenteditable/pull/51

**Comment by nijk** [comment]
@paschaldev @jstriebel @ashleyw @kjrandez 

Just a quick heads up to say that I'm pretty close to raising a PR that makes some pretty big changes to the internals of this component as suggested on point number 5 of #33.

If you'd like early sight of this work or could help me out with a bit of testing then I'd appreciate it. I'm currently aware of a few minor bugs when using the `multiLine` prop.

[The work is this branch](https://github.com/ashleyw/react-sane-contenteditable/tree/33-improve-props-pattern)

**Comment by pfischer1290** [comment]
@nijk thx for the response, appreciate your effort.

Anyone who needs my PR as a temporary fix while waiting for the new version form njik: 
-> just use the PRs state as npm tarball like so:

```
"react-sane-contenteditable": "https://github.com/pfischer1290/react-sane-contenteditable/tarball/626b94ce3a938f9ba198b66d0eb72b5621c39462",
```

**Comment by nijk** [comment]
@paschaldev @jstriebel @ashleyw @kjrandez

[PR here](#52)

Any help with testing would be greatly appreciated
