### ISSUE TITLE
Controlled Component Issues

### ISSUE THREAD

**Issue by iAziz786** [ashleyw/react-sane-contenteditable#42]
Firstly, thanks for this awesome, lite, and simple component. If I haven't been able to explain the issue correctly please ask, I'll try to be more descriptive.

Codesandbox: https://codesandbox.io/s/24n6xqz6vp

I was trying to use this component into one of my projects. For some reason, I want to keep track of typed text into my **redux** state. So, I thought it would be best to make this component into a controlled component. But when I started to control the state (which I've passed through `content` prop) I got myself into some of the issues:

1. Controlling the state of this component caused it to keep losing focus after each `onKeyDown` (after which I'm setting the state) event.
2. I thought that setting `focus` prop to `true` will fix this issue but that causes some other problem. Now I'm not losing the focus but after each `onKeyDown` event my `caretPosition` is jumping back to the start of the text.
3. Then again I thought that setting `caretPosition` to `end` will fix this issue but that causes some other problem. **THE APP BREAKS** :face_with_head_bandage: 

I have **mapped** the issues through comments in the sandbox link.
Also, If I can help in any sort I would love to. That will also help me for the Hacktoberfest.

**Comment by nijk** [comment]
Hi @iAziz786,

You were really close with the props you provided,  just change `innerRef` to `ref` or remove it completely: https://codesandbox.io/s/5k4ymlw24k

**Comment by iAziz786** [comment]
Thanks, @nijk! This helps. But one thing is still not clear. Why setting `caretPosition` to value `end` breaks the app?

**Comment by nijk** [comment]
No problem at all @iAziz786 

The issue is with the way that `caretPosition` calculates where to place the caret, I've raised a [bug here](#44).
