### ISSUE TITLE
setCaret should only set offset to 1 if state.value has length

### ISSUE THREAD

**Issue by nijk** [ashleyw/react-sane-contenteditable#44]
[Issue demonstrated here](https://codesandbox.io/s/nn4m252mzl).

**Comment by iAziz786** [comment]
Thanks for this fix. @nijk

**Comment by iAziz786** [comment]
Should bump the version?

**Comment by nijk** [comment]
@iAziz786 Feel free to use this commit hash in your `package.json` or wait until the npm package has been updated. This is a job for @ashleyw as he is the package owner

**Comment by nijk** [comment]
@iAziz786 FYI: the way to use this immediately would be:

`npm install --save yarn add git+https://github.com/ashleyw/react-sane-contenteditable.git#4d317c0`
or
`yarn add git+https://github.com/ashleyw/react-sane-contenteditable.git#4d317c0`

**Comment by macrozone** [comment]
can we merge and publish? i just fell into this trap  as well ;-)

**Comment by iAziz786** [comment]
@macrozone Fix for this has already been merged in #45 , only waiting for @ashleyw to update the version and publish it to npm.

Meanwhile, you can do this:

> npm install --save git+https://github.com/ashleyw/react-sane-contenteditable.git#4d317c0
> or
> yarn add git+https://github.com/ashleyw/react-sane-contenteditable.git#4d317c0
> 

to have fixed version. I understand this looks little ugly to do but fix the problem for now.

**Comment by nijk** [comment]
@ashleyw This one is for you :)

**Comment by nijk** [comment]
@iAziz786 @macrozone v1.5.0 now published on npm: https://www.npmjs.com/package/react-sane-contenteditable/v/1.5.0
