### ISSUE TITLE
Field loses focus when using useState hook

### ISSUE THREAD

**Issue by ericmand** [ashleyw/react-sane-contenteditable#48]
I have a working component that I'm rewriting to use the new React Hooks. Unfortunately, the rewritten component loses focus with every keystroke. 

While using:
react@16.7.0-alpha.0
react-dom@16.7.0-alpha.0

The following works great (keeps focus with each keystroke):
```javascript
import React, { Component } from 'react';

export default class ItemNode extends Component {
  constructor(props) {
    super(props);
    this.state = {
      content: props.content
    };
  }

  handleChange(e, value){
    this.setState({ content: value });
  }
  
  render() {
    return (
      <div>
        <ContentEditable 
          content={this.state.content}
          editable={true}
          multiLine={false}
          onChange={this.handleChange}
        />
      </div>
    );
  }
}
```

The following breaks (loses focus with each keystroke)
```javascript
import React, { useState } from 'react';

function App(props){
  const [content, setContent] = useState('blah');
  
  function handleChange(e, value){
    setContent(value);
  }
  return (
    <div>
      <ContentEditable 
        content={content}
        editable={true}
        multiLine={false}
        onChange={handleChange}
      />
    </div>
  );
}

export default App;
```

**Comment by nijk** [comment]
Hi @ericmand, could you create a [codesandbox](https://codesandbox.io/) example of the issue please?

**Comment by ericmand** [comment]
Created a codesandbox and things are working just fine. Must be something in my environment. Sorry for the trouble.

**Comment by nijk** [comment]
@ericmand No problem at all, thanks for putting the effort in to replicate it in an isolated environment

**Comment by saraogipraveen** [comment]
> Created a codesandbox and things are working just fine. Must be something in my environment. Sorry for the trouble.

@ericmand
Even I am facing this same issue, can you tell what environment problem you had??

**Comment by soaresdiogo** [comment]
So do I, same problem
