### ISSUE TITLE
Cursor jumps to start with latest v1.3.0 update

### ISSUE THREAD

**Issue by tennisgent** [ashleyw/react-sane-contenteditable#8]
First of all, thanks for this component. It's been working great up until this latest update. 

Now, whenever I type into the element, the cursor jumps to the front of the element with every key that is entered. I've rolled back to `v1.2.0` and everything works fine again. But if I reinstall `v1.3.0`, the cursor starts behaving funny again. I've locked my dependency back to `v1.2.0` for now, so I'm okay for the time being.

I'm not sure what changed in that latest version to cause that behavior, but thought I should report it. Let me know if you need any further info from me. 

FYI, this is on `Chrome 65.0.3325.181`

**Comment by ashleyw** [comment]
Fixed in 1.3.1! 🎉

The culprit? `without(Object.keys(propTypes), ["content"])` should have been `without(Object.keys(propTypes), "content")`

**Comment by tennisgent** [comment]
Awesome. Thanks!
